java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_CONNECTION_OPTIONS: "?sslmode=allow"

    SPRING_LIQUIBASE_ENABLED: true
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/hmcts
    LAUNCH_DARKLY_USER_NAME_PREFIX: aat
    SPRING_PROFILES_ACTIVE: "liberataMock,callbackMock,ccdMock"
    CALLBACK_PAYMENTS_CUTOFF_TIME_IN_MINUTES: 0

    #Below key required for preview pipeline
    GOV_PAY_AUTH_KEY_CMC: 8ln764q6jrbgqvvvv40uggsea3h1p602v79gdrt7ni66mrmpk416ulohvd
    LAUNCH_DARKLY_SDK_KEY: sdk-06456c8b-312c-475c-b154-ca585f5ca063
    CCPAY_BULK_SCANNING_API_URL: http://ccpay-bulkscanning-api-aat.service.core-compute-aat.internal
    PAYMENT_S2S_SECRET: ETNY5CBN7NR62T6M
    card.payments.email.to: Krishna.Nuthalapati@hmcts.net
    bar.payments.email.to: Krishna.Nuthalapati@hmcts.net
    pba.cmc.payments.email.to: Krishna.Nuthalapati@hmcts.net
    pba.probate.payments.email.to: Krishna.Nuthalapati@hmcts.net
    pba.finrem.payments.email.to: Krishna.Nuthalapati@hmcts.net
    pba.divorce.payments.email.to: Krishna.Nuthalapati@hmcts.net
    pba.fpl.payments.email.to: Krishna.Nuthalapati@hmcts.net

    PCI_PAL_API_URL: https://ip3cloud.com/clients/hmcts/payments/index.php
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - gov-pay-keys-cmc
        - launch-darkly-sdk-key
        - payment-s2s-secret
        - pci-pal-antenna-tenant-name
        - pci-pal-antenna-user-name
        - pci-pal-antenna-client-id
        - pci-pal-antenna-client-secret
        - pci-pal-antenna-get-tokens-url
        - pci-pal-antenna-launch-url
        - pci-pal-antenna-view-id-url
        - pci-pal-antenna-return-url
        - pci-pal-antenna-cmc-flow-id
        - pci-pal-antenna-probate-flow-id
        - pci-pal-antenna-divorce-flow-id
        - pci-pal-antenna-financial-remedy-flow-id
        - spring-mail-password
  postgresql:
    enabled: true
