java:
  image: hmctspublic.azurecr.io/payment/api:latest
  applicationPort: 8080
  ingressHost: payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccpay
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_HOST: payment-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_NAME: payment
    POSTGRES_USERNAME: payment@payment-postgres-db-{{ .Values.global.environment }}
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: false

    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    REFORM_SERVICE_NAME: payment-api
    REFORM_TEAM: cc

    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    FEES_REGISTER_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAYBUBBLE_HOME_URL: https://ccpay-bubble-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CORE_CASE_DATA_API_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    GOV_PAY_URL: "https://publicapi.payments.service.gov.uk/v1/payments"
    GOV_PAY_OPERATIONAL_SERVICES: "ccd_gw"
    PCI_PAL_CALLBACK_URL: https://core-api-mgmt-{{ .Values.global.environment }}.azure-api.net/telephony-api/telephony/callback

    TRUSTED_S2S_SERVICE_NAMES: "cmc,cmc_claim_store,probate_frontend,divorce_frontend,ccd_gw,bar_api,api_gw,finrem_payment_service,ccpay_bubble,jui_webapp,xui_webapp,fpl_case_service"
    
    CARD_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    CARD_PAYMENTS_EMAIL_FROM: "no-reply@reform.hmcts.net"
    CARD_PAYMENTS_EMAIL_MESSAGE: "hi"
    CARD_PAYMENTS_EMAIL_SUBJECT: "Docker Env Card Payments Reconciliation Report"

    BAR_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    BAR_PAYMENTS_EMAIL_FROM: "no-reply@reform.hmcts.net"
    BAR_PAYMENTS_EMAIL_MESSAGE: "hi"
    BAR_PAYMENTS_EMAIL_SUBJECT: "Docker Env Bar Payments Reconciliation Report"

    PBA_CMC_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_CMC_PAYMENTS_EMAIL_FROM: "no-reply@reform.hmcts.net"
    PBA_CMC_PAYMENTS_EMAIL_MESSAGE: "hi"
    PBA_CMC_PAYMENTS_EMAIL_SUBJECT: "Docker Env Card Payments Reconciliation Report"

    PBA_PROBATE_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_PROBATE_PAYMENTS_EMAIL_FROM: "no-reply@reform.hmcts.net"
    PBA_PROBATE_PAYMENTS_EMAIL_MESSAGE: "hi"
    PBA_PROBATE_PAYMENTS_EMAIL_SUBJECT: "Docker Env Card Payments Reconciliation Report"

    PBA_FINREM_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_FINREM_PAYMENTS_EMAIL_FROM: "no-reply@reform.hmcts.net"
    PBA_FINREM_PAYMENTS_EMAIL_MESSAGE: "hi"
    PBA_FINREM_PAYMENTS_EMAIL_SUBJECT: "Docker Env Card Payments Reconciliation Report"

    PBA_DIVORCE_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_DIVORCE_PAYMENTS_EMAIL_FROM: "no-reply@reform.hmcts.net"
    PBA_DIVORCE_PAYMENTS_EMAIL_MESSAGE: "hi"
    PBA_DIVORCE_PAYMENTS_EMAIL_SUBJECT: "Docker Env Card Payments Reconciliation Report"

    PBA_FPL_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_FPL_PAYMENTS_EMAIL_FROM: "no-reply@reform.hmcts.net"
    PBA_FPL_PAYMENTS_EMAIL_MESSAGE: "hi"
    PBA_FPL_PAYMENTS_EMAIL_SUBJECT: "Docker Env Card Payments Reconciliation Report"

    SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: "*"
    SPRING_MAIL_PORT: "25"
    SPRING_MAIL_HOST: "mta.reform.hmcts.net"

    FEATURE_PAYMENTS_SEARCH: "true"
    FEATURE_SERVICE_CALLBACK: "true"


  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - api-POSTGRES-PASS
        - sb-primary-connection-string
        - pci-pal-account-id-cmc
        - pci-pal-account-id-probate
        - pci-pal-account-id-divorce
        - pci-pal-api-url
        - pci-pal-api-key
        - gov-pay-keys-reference
        - gov-pay-keys-cmc
        - gov-pay-keys-cmc-claim-store
        - gov-pay-keys-divorce
        - gov-pay-keys-probate
        - liberata-keys-oauth2-client-id
        - liberata-keys-oauth2-client-secret
        - liberata-keys-oauth2-username
        - liberata-keys-oauth2-password
        - AppInsightsInstrumentationKey
        - card-payments-email-to
        - bar-payments-email-to
        - pba-fpl-payments-email-to
        - pba-divorce-payments-email-to
        - pba-payments-email-to

