ccpay-refunds-api:
  enabled: false
ccpay-bulkscanning-api:
  enabled: false
ccpay-notifications-service:
  enabled: false

java:
  image: hmctspublic.azurecr.io/payment/api:latest
  applicationPort: 8080
  ingressHost: payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ccpay
  environment:
    POSTGRES_NAME: payment
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: false

    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    REFORM_SERVICE_NAME: payment-api
    REFORM_TEAM: cc
    ISSUER_URI: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o"
    OIDC_CLIENT_ID: "paybubble"
    OIDC_ISSUER: "https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts"
    OIDC_S2S_MICROSERVICE_NAME: ccpay_bubble
    OIDC_AUDIENCE_LIST: paybubble,iac,cmc_citizen,probate,divorce,xuiwebapp,xuimowebapp,xuiaowebapp,fees_admin_frontend,finrem,bar_frontend,fpl_case_service,ccd_gateway
    LAUNCH_DARKLY_USER_NAME_PREFIX: '{{ .Values.global.environment }}'

    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    AUTH_REF_DATA_BASEURL: http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEES_REGISTER_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAYBUBBLE_HOME_URL: https://ccpay-bubble-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CORE_CASE_DATA_API_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CASE_PAYMENT_ORDERS_API_URL: http://cpo-case-payment-orders-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CCPAY_BULK_SCANNING_API_URL: http://ccpay-bulkscanning-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IAC_SERVICE_API_URL: http://ia-case-access-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CALLBACK_PAYMENTS_CUTOFF_TIME_IN_MINUTES: 2

    GOV_PAY_URL: "https://publicapi.payments.service.gov.uk/v1/payments"
    GOV_PAY_OPERATIONAL_SERVICES: "ccd_gw,api_gw,xui_webapp,ccpay_gw"
    PCI_PAL_CALLBACK_URL: https://cft-mtls-api-mgmt-appgw.{{ .Values.global.environment }}.platform.hmcts.net/telephony-api/telephony/callback

    TRUSTED_S2S_SERVICE_NAMES: "refunds_api,iac,cmc,cmc_claim_store,probate_frontend,divorce_frontend,ccd_gw,api_gw,finrem_payment_service,ccpay_bubble,jui_webapp,xui_webapp,fpl_case_service,civil_service,paymentoutcome_web,adoption_web,prl_cos_api,notifications_service,ccpay_gw,pcs_api"
    CARD_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    CARD_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    CARD_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    CARD_PAYMENTS_EMAIL_SUBJECT: "CNP:Card Payments Reconciliation Report"
    PBA_PROBATE_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_PROBATE_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_PROBATE_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_PROBATE_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA Probate Reconciliation Report"
    PBA_FINREM_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_FINREM_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_FINREM_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_FINREM_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA Financial Remedy Reconciliation Report"
    PBA_DIVORCE_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_DIVORCE_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_DIVORCE_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_DIVORCE_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA Divorce Reconciliation Report"
    PBA_FPL_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_FPL_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_FPL_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_FPL_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA FPL Reconciliation Report"
    PBA_PRL_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_PRL_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_PRL_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_PRL_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA PRL Reconciliation Report"
    PBA_CIVIL_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_CIVIL_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_CIVIL_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_CIVIL_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA Civil Damages Reconciliation Report"
    PBA_IAC_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_IAC_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_IAC_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_IAC_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA IAC Reconciliation Report"
    DUPLICATE_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    DUPLICATE_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    DUPLICATE_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Potential Duplicate Payments report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    DUPLICATE_PAYMENTS_EMAIL_SUBJECT: "CNP:Potential Duplicate Payments Report"
    PBA_SMC_PAYMENTS_REPORT_SCHEDULER_ENABLED: "true"
    PBA_SMC_PAYMENTS_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    PBA_SMC_PAYMENTS_EMAIL_MESSAGE: "Hi, <br/><br/>Please find attached Payment by Account reconciliation report. <br/><br/>Regards, <br/>Fees & Payments Team <br/><br/>"
    PBA_SMC_PAYMENTS_EMAIL_SUBJECT: "CNP:PBA Specified Money Claims Reconciliation Report"
    DUPLICATE_SERVICE_REQUEST_REPORT_SCHEDULER_ENABLED: "true"
    DUPLICATE_SERVICE_REQUEST_EMAIL_FROM: "no-reply@mail-payment-nonprod.platform.hmcts.net"
    DUPLICATE_SERVICE_REQUEST_EMAIL_SUBJECT: "CNP:Service Request Report"
    DUPLICATE_SERVICE_REQUEST_EMAIL_MESSAGE: "Hi <br/><br/>Please find attached today's Duplicate Service Request report. <br/><br/>Regards <br/><br/>Payments team <br/><br/>"
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: "smtp.sendgrid.net"
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_PROTOCOLS: "TLSv1.2"
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_SMTP_AUTH: true
    SPRING_MAIL_PORT: "587"
    SPRING_MAIL_HOST: "smtp.sendgrid.net"
    SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
    SPRING_MAIL_USERNAME: apikey

    FEATURE_PAYMENTS_SEARCH: "true"
    FEATURE_SERVICE_CALLBACK: "true"
    PAYMENT_S2S_MICROSERVICE_NAME: payment_app
    PBA_CONFIG1_SERVICE_NAMES: dummy
    RD_LOCATION_BASE_URL: http://rd-location-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    REFUND_API_URL: http://ccpay-refunds-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVER_SHUTDOWN_STRATEGY: graceful
    TIMEOUT_SERVER_SHUTDOWN_PHASE: 30s

    CARD_LAG_TIME: 120
    CASH_LAG_TIME: 120
    POSTALORDER_LAG_TIME: 480
    CHEQUES_LAG_TIME: 480
    PBA_LAG_TIME: 96

    CPO_SELECT_ACCOUNT_GRANT_TYPE: password
    CPO_SELECT_ACCOUNT_SCOPE: openid profile roles

  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - name: sb-premium-primary-connection-string
          alias: azure.servicebus.connection-string
        - name: pci-pal-account-id-probate
          alias: pci-pal.account.id.probate
        - name: pci-pal-account-id-divorce
          alias: pci-pal.account.id.divorce
        - name: pci-pal-account-id-strategic
          alias: pci-pal.account.id.strategic
        - name: pci-pal-api-url
          alias: pci-pal.api.url
        - name: pci-pal-api-key
          alias: pci-pal.api.key
        - name: gov-pay-keys-reference
          alias: GOV_PAY_AUTH_KEY_REFERENCE
        - name: gov-pay-keys-cmc
          alias: gov.pay.auth.key.cmc
        - name: gov-pay-keys-cmc
          alias: gov.pay.auth.key.civil_service
        - name: gov-pay-keys-cmc-claim-store
          alias: gov.pay.auth.key.cmc_claim_store
        - name: gov-pay-keys-divorce
          alias: gov.pay.auth.key.divorce_frontend
        - name: gov-pay-keys-divorce
          alias: gov.pay.auth.key.nfdiv_case_api
        - name: gov-pay-keys-probate
          alias: gov.pay.auth.key.probate_frontend
        - name: gov-pay-keys-iac
          alias: gov.pay.auth.key.iac
        - name: gov-pay-keys-adoption
          alias: gov.pay.auth.key.adoption_web
        - name: gov-pay-keys-prl
          alias: gov.pay.auth.key.prl_cos_api
        - name: liberata-keys-oauth2-client-id
          alias: liberata.oauth2.client.id
        - name: liberata-keys-oauth2-client-secret
          alias: liberata.oauth2.client.secret
        - name: liberata-keys-oauth2-username
          alias: liberata.oauth2.username
        - name: liberata-keys-oauth2-password
          alias: liberata.oauth2.password
        - name: api-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
        - name: api-POSTGRES-PORT
          alias: POSTGRES_PORT
        - name: api-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: api-POSTGRES-USER
          alias: POSTGRES_USERNAME
        - name: core-case-data-api-url
          alias: core_case_data.api.url
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: card-payments-email-to
          alias: card.payments.email.to
        - name: pba-probate-payments-email-to
          alias: pba.probate.payments.email.to
        - name: pba-finrem-payments-email-to
          alias: pba.finrem.payments.email.to
        - name: pba-divorce-payments-email-to
          alias: pba.divorce.payments.email.to
        - name: pba-fpl-payments-email-to
          alias: pba.fpl.payments.email.to
        - name: pba-civil-payments-email-to
          alias: pba.civil.payments.email.to
        - name: pba-prl-payments-email-to
          alias: pba.prl.payments.email.to
        - name: pba-iac-payments-email-to
          alias: pba.iac.payments.email.to
        - name: launch-darkly-sdk-key
          alias: launch.darkly.sdk.key
        - name: payment-s2s-secret
          alias: PAYMENT_S2S_SECRET
        - name: pci-pal-antenna-tenant-name
          alias: pci-pal.antenna.tenant.name
        - name: pci-pal-antenna-user-name
          alias: pci-pal.antenna.user.name
        - name: pci-pal-antenna-client-id
          alias: pci-pal.antenna.client.id
        - name: pci-pal-antenna-client-secret
          alias: pci-pal.antenna.client.secret
        - name: pci-pal-antenna-get-tokens-url
          alias: pci-pal.antenna.get.tokens.url
        - name: pci-pal-antenna-launch-url
          alias: pci-pal.antenna.launch.url
        - name: pci-pal-antenna-view-id-url
          alias: pci-pal.antenna.view.id.url
        - name: pci-pal-antenna-return-url
          alias: pci-pal.antenna.return.url
        - name: pci-pal-antenna-probate-flow-id
          alias: pci-pal.antenna.probate.flow.id
        - name: pci-pal-antenna-divorce-flow-id
          alias: pci-pal.antenna.divorce.flow.id
        - name: pci-pal-antenna-prl-flow-id
          alias: pci-pal.antenna.prl.flow.id
        - name: pci-pal-antenna-iac-flow-id
          alias: pci-pal.antenna.iac.flow.id
        - name: pci-pal-antenna-strategic-flow-id
          alias: pci-pal.antenna.strategic.flow.id
        - name: pci-pal-kerv-tenant-name
          alias: pci-pal.kerv.tenant.name
        - name: pci-pal-kerv-client-id
          alias: pci-pal.kerv.client.id
        - name: pci-pal-kerv-client-secret
          alias: pci-pal.kerv.client.secret
        - name: pci-pal-kerv-get-tokens-url
          alias: pci-pal.kerv.get.tokens.url
        - name: pci-pal-kerv-launch-url
          alias: pci-pal.kerv.launch.url
        - name: pci-pal-kerv-view-id-url
          alias: pci-pal.kerv.view.id.url
        - name: pci-pal-kerv-probate-flow-id
          alias: pci-pal.kerv.probate.flow.id
        - name: pci-pal-kerv-divorce-flow-id
          alias: pci-pal.kerv.divorce.flow.id
        - name: pci-pal-kerv-prl-flow-id
          alias: pci-pal.kerv.prl.flow.id
        - name: pci-pal-kerv-iac-flow-id
          alias: pci-pal.kerv.iac.flow.id
        - name: pci-pal-kerv-strategic-flow-id
          alias: pci-pal.kerv.strategic.flow.id
        - name: spring-mail-password
          alias: spring.mail.password
        - name: ccpay-payment-status-connection-string
          alias: ccpay-payment-status-connection-string
        - name: pba-smc-payments-email-to
          alias: pba.smc.payments.email.to
        - name: duplicate-payments-email-to
          alias: duplicate.payments.email.to
        - name: service-request-email-to
          alias: service.request.email.to

