postgresql:
  enabled: true
java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    SPRING_PROFILES_ACTIVE: "liberataMock,callbackMock,ccdMock"
    CALLBACK_PAYMENTS_CUTOFF_TIME_IN_MINUTES: 0
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    AUTH_IDAM_CLIENT_BASEURL: "https://idam-api.aat.platform.hmcts.net"
